name: PromoMeCompany
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Lists & Grids
  flutter_staggered_grid_view: 0.3.0

  # Media
  extended_image: 0.9.0
  cached_network_image: ^2.1.0+1
  flutter_svg: ^0.18.0

  # Bloc
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  provider:

  firebase_messaging: ^7.0.0
  # Localizations
  intl: ^0.16.0

  # Utils
  fluttertoast: ^3.1.3
  loading_indicator_view: ^1.0.0

  # Storage
  shared_preferences: ^0.5.6+1

  # Network
  http: ^0.12.0+2

  # Others
  shimmer: ^1.1.1
  font_awesome_flutter: ^8.8.1
  html_unescape: 1.0.1+3
  cupertino_icons: ^0.1.3
  flutter_rating_bar: ^3.0.1+1
  extended_nested_scroll_view: ^1.0.1
  quiver: ^2.1.3
  bubble_tab_indicator: ^0.1.4
  scroll_to_index: ^1.0.6
  carousel_pro: ^1.0.0
  incrementally_loading_listview: ^0.3.0
  custom_navigation_bar: ^0.2.7
  animated_bottom_navigation_bar: ^0.1.2+2
  flutter_stories: ^0.2.1+1
  video_player: 0.11.1+5
  url_launcher: ^5.7.10
  badges: ^1.1.0
  image_picker: ^0.6.3+4
  image_cropper: ^1.3.1
  multi_select_flutter: ^3.1.6
  mime_type: ^0.3.2



  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  build_runner: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"


flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/sf-pro-display-regular.otf
        - asset: assets/fonts/sf-pro-display-light.otf
        - asset: assets/fonts/sf-pro-display-bold.otf
        - asset: assets/fonts/sf-pro-display-medium.otf
        - asset: assets/fonts/sf-pro-display-black.otf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Black.ttf